{
 "title": "ADS-B",
 "description": "Used to visualise metrics collected from the mikenye/readsb-protobuf docker image.",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "show tag values from \"readsb\" with key = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Maps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
     "options": {
      "content": "<iframe src=\"https://tar1090.challa.co:1982/\" title=\"Map\" style=\"width:100%; height:100%; padding:0; margin:0; border:none;\"></iframe>         "
     },
     "targets": [
      {}
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
     "options": {
      "content": "<iframe src=\"https://tar10901.challa.co:1982\" title=\"Map\" style=\"width:100%; height:100%; padding:0; margin:0; border:none;\"></iframe>         "
     }
    }
   ]
  },
  {
   "title": "System Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "rtlsdr - Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_rtlsdr_temp",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "rtlsdr - CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 +100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "rtlsdr" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "rtlsdr - RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "RAM" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "rtlsdr" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "rtlsdr - Uptime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"uptime\") FROM \"system\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "rtlsdr" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Radxa - CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_radexa_zero_temp",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "DietPi" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Radxa - CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 +100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "DietPi" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Radxa - RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "RAM" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "DietPi" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Radxa - Uptime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"uptime\") FROM \"system\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "DietPi" }
     ]
    }
   ]
  },
  {
   "title": "ADS-B Statistics - $hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "hostname",
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Aircraft - $hostname",
     "measurement": "readsb",
     "query": "SELECT last(\"Lat\") FROM \"aircraft\" WHERE (\"host\" = 'readsb' AND \"Icao\" != '') AND time >= now() - 1m GROUP BY \"Icao\"",
     "select": [
      [
       { "params": [ "tracks_with_position" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "readsb",
     "query": "SELECT sum(\"local_accepted\") AS \"local_accepted\", sum(\"local_strong_signals\") AS \"local_strong_signals\" FROM \"readsb\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "local_accepted" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "local_accepted" ], "type": "alias" }
      ],
      [
       { "params": [ "local_strong_signals" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "local_strong_signals" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "max_distance_in_metres" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*0.000621" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "max_distance_in_metres" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*0.000621" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "type": "snuids-radar-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "bearing" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "polar_range",
     "select": [
      [
       { "params": [ "range" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "readsb",
     "query": "SELECT mean(\"local_signal\") AS \"signal\", mean(\"local_noise\") AS \"noise\" FROM \"readsb\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "local_signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "signal" ], "type": "alias" }
      ],
      [
       { "params": [ "local_noise" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "noise" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "max_distance_in_metres" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*0.000621" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "readsb",
     "select": [
      [
       { "params": [ "max_distance_in_metres" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*0.000621" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Aircraft Count History - $hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "hostname",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Aircraft Seen ",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "# of Aircraft",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "readsb",
       "query": "SELECT max(\"tracks_with_position\") FROM \"readsb\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($interval) fill(none)",
       "select": [
        [
         { "params": [ "tracks_with_position" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Performance Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "User",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "rtlsdr" }
       ]
      },
      {
       "alias": "System",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "rtlsdr" }
       ]
      },
      {
       "alias": "IoWait",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_iowait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "Temp",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "exec_rtlsdr_temp",
       "select": [
        [
         { "params": [ "cpu" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ]
      },
      {
       "alias": "Temp Max",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "exec_rtlsdr_temp",
       "query": "SELECT max(\"cpu\")  / 1000 FROM \"exec_rtlsdr_temp\" WHERE $timeFilter GROUP BY time(1d) fill(previous)",
       "select": [
        [
         { "params": [ "cpu" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ]
      },
      {
       "alias": "Temp Min",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "exec_rtlsdr_temp",
       "select": [
        [
         { "params": [ "cpu" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Radxa Zero CPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "alias": "CPU Temperature",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "exec_radexa_zero_temp",
       "select": [
        [
         { "params": [ "cpu" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DietPi" }
       ]
      },
      {
       "alias": "CPU Usage",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_nice" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DietPi" }
       ]
      }
     ]
    },
    {
     "title": "Message Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Messages Received",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "readsb",
       "select": [
        [
         { "params": [ "messages" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "Messages > 3dbFS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "readsb",
       "select": [
        [
         { "params": [ "local_strong_signals" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "Positions/s (RHS)",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "readsb",
       "select": [
        [
         { "params": [ "cpr_global_ok" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "/60" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Tracks Seen",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Tracks",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "readsb",
       "select": [
        [
         { "params": [ "tracks_with_position" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "Tracks with single message",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "readsb",
       "select": [
        [
         { "params": [ "tracks_single_message" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Positions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ADS-B",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "readsb",
       "select": [
        [
         { "params": [ "tracks_with_position" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "MLAT",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "readsb",
       "select": [
        [
         { "params": [ "tracks_mlat_position" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "TIS-B",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "readsb",
       "select": [
        [
         { "params": [ "tracks_tisb_position" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Current Aircraft",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Currently Tracked Aircraft",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "Icao" ], "type": "tag" },
        { "params": [ "Call" ], "type": "tag" }
       ],
       "measurement": "aircraft",
       "query": "SELECT last(\"Lat\"), \"Long\", \"Alt\", \"Cmsgs\", \"GAlt\", \"InHg\", \"PosTime\", \"Sig\", \"Spd\", \"TAlt\", \"TTrk\", \"Trak\", \"Trt\", \"Vsi\" FROM \"aircraft\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"Icao\", \"Call\"",
       "select": [
        [
         { "params": [ "Lat" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ],
        [
         { "params": [ "Long" ], "type": "field" }
        ],
        [
         { "params": [ "Alt" ], "type": "field" }
        ],
        [
         { "params": [ "Cmsgs" ], "type": "field" }
        ],
        [
         { "params": [ "GAlt" ], "type": "field" }
        ],
        [
         { "params": [ "InHg" ], "type": "field" }
        ],
        [
         { "params": [ "PosTime" ], "type": "field" }
        ],
        [
         { "params": [ "Sig" ], "type": "field" }
        ],
        [
         { "params": [ "Spd" ], "type": "field" }
        ],
        [
         { "params": [ "TAlt" ], "type": "field" }
        ],
        [
         { "params": [ "TTrk" ], "type": "field" }
        ],
        [
         { "params": [ "Trak" ], "type": "field" }
        ],
        [
         { "params": [ "Trt" ], "type": "field" }
        ],
        [
         { "params": [ "Vsi" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Autogain - $hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "hostname",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Autogain: Gain Levels",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "yaxes": [
      { "format": "dB" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "autogain",
       "select": [
        [
         { "params": [ "autogain_current_value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "current" ], "type": "alias" }
        ],
        [
         { "params": [ "autogain_max_value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "max" ], "type": "alias" }
        ],
        [
         { "params": [ "autogain_min_value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         },
         { "params": [ "min" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "readsb",
       "query": "SELECT mean(\"local_signal\") AS \"signal\", mean(\"local_noise\") AS \"noise\" FROM \"readsb\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "local_signal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "signal" ], "type": "alias" }
        ],
        [
         { "params": [ "local_noise" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "noise" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "yaxes": [
      { "format": "dB" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "readsb",
       "query": "SELECT mean(\"local_signal\") AS \"signal\", mean(\"local_noise\") AS \"noise\" FROM \"readsb\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "local_signal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "signal" ], "type": "alias" }
        ],
        [
         { "params": [ "local_noise" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "noise" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "readsb",
       "query": "SELECT sum(\"local_accepted\") AS \"local_accepted\", sum(\"local_strong_signals\") AS \"local_strong_signals\" FROM \"readsb\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "local_accepted" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "local_accepted" ], "type": "alias" }
        ],
        [
         { "params": [ "local_strong_signals" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "local_strong_signals" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Signal Strength",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 107 },
     "yaxes": [
      { "format": "dB" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "readsb",
       "select": [
        [
         { "params": [ "local_signal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Signal" ], "type": "alias" }
        ],
        [
         { "params": [ "local_noise" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Noise" ], "type": "alias" }
        ],
        [
         { "params": [ "local_peak_signal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Peak Signal" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}